####
# autocoder/fprime_python.cmake:
#
# CMake implementation of an fprime autocoder used to generate Python bindings for components, types, etc. This
# autocoder uses the same autocoding criteria that the FPP autocoder uses, however; it assumes that the
# fprime-python-model compatible output has been generated in the build cache.
####
include_guard()
include(utilities)
include(autocoder/helpers)

set(FPRIME_PYTHON_PYTHON_PATH "${CMAKE_CURRENT_LIST_DIR}" CACHE STRING "Path to fprime-python package")
# Invoke the autocoder once for each module containing FPP files.
autocoder_setup_for_multiple_sources()

####
# Function `is_supported`:
#
# Required function, processes module that contain FPP files.
# `AC_INPUT_FILE` potential input to the autocoder
####
function(fprime_python_is_supported AC_INPUT_FILE)
    autocoder_support_by_suffix(".fpp" "${AC_INPUT_FILE}" TRUE)
endfunction(fprime_python_is_supported)


####
# Function `fprime_python_setup_autocode`:
#
# Sets up the steps to run the autocoder and produce the files during the build. This is passed the lists generated
# in calls to `get_generated_files` and `get_dependencies`.
#
# AC_INPUT_FILES: list of supported autocoder input files
####
function(fprime_python_setup_autocode MODULE_NAME AC_INPUT_FILES)
    find_program(PYTHON NAMES python3 python REQUIRED)
    fprime_cmake_ASSERT("'python' nor 'python3' found" NOT "${PYTHON}" MATCHES ".*-NOTFOUND")
    set(ENV{PYTHONPATH} "${FPRIME_PYTHON_PYTHON_PATH}")
    execute_process(
        COMMAND "${PYTHON}" -m "fprime_python" "bindings" "${CMAKE_CURRENT_BINARY_DIR}" "--dry-run" "--output-directory" "${CMAKE_CURRENT_BINARY_DIR}" --prefixes ${FPRIME_BUILD_LOCATIONS} "--translation-units" ${AC_INPUT_FILES}
        OUTPUT_VARIABLE GENERATED_FILES_RAW
    )
    string(REPLACE " " ";" GENERATED_FILES_LIST "${GENERATED_FILES_RAW}")
    string(REPLACE "\n" "" GENERATED_FILES_LIST "${GENERATED_FILES_LIST}")
    get_target_property(MODULE_TYPE ${MODULE_NAME} TYPE)
    # Output was generated by this autocoder
    if (GENERATED_FILES_LIST AND NOT MODULE_TYPE STREQUAL "INTERFACE_LIBRARY")
        set(GENERATED_CPP_FILES "${GENERATED_FILES_LIST}")
        set(GENERATED_HPP_FILES "${GENERATED_FILES_LIST}")
        set(GENERATED_JSON_FILES "${GENERATED_FILES_LIST}")
        list(FILTER GENERATED_CPP_FILES INCLUDE REGEX "^.*\\.cpp$")
        list(FILTER GENERATED_HPP_FILES INCLUDE REGEX "^.*\\.hpp$")
        list(FILTER GENERATED_JSON_FILES INCLUDE REGEX "^.*\\.json$")

        append_list_property("${GENERATED_HPP_FILES}" TARGET "${MODULE_NAME}" PROPERTY FPRIME_PYTHON_GENERATED_HPP_FILES)
        append_list_property("${GENERATED_JSON_FILES}" TARGET "${MODULE_NAME}" PROPERTY FPRIME_PYTHON_GENERATED_JSON_FILES)

        add_custom_command(
            OUTPUT ${GENERATED_HPP_FILES} ${GENERATED_CPP_FILES} ${GENERATED_JSON_FILES}
            DEPENDS ${AC_INPUT_FILES}
            COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=${FPRIME_PYTHON_PYTHON_PATH}
                    "${PYTHON}" -m "fprime_python" "bindings" "${CMAKE_CURRENT_BINARY_DIR}" "--output-directory" "${CMAKE_CURRENT_BINARY_DIR}" --prefixes ${FPRIME_BUILD_LOCATIONS} "--translation-units" ${AC_INPUT_FILES}
        )

        set(AUTOCODER_DEPENDENCIES "pybind11::pybind11" PARENT_SCOPE)
        # TODO: what are our output sources here?
        set(AUTOCODER_GENERATED_BUILD_SOURCES ${GENERATED_CPP_FILES} PARENT_SCOPE)
        # Generate HPP files as OTHER outputs since these technically are not built
        set(AUTOCODER_GENERATED_OTHER ${GENERATED_HPP_FILES} ${GENERATED_JSON_FILES} PARENT_SCOPE)
    else()
        # No files were generated
        set(AUTOCODER_DEPENDENCIES "" PARENT_SCOPE)
        set(AUTOCODER_GENERATED_BUILD_SOURCES "" PARENT_SCOPE)
        set(AUTOCODER_GENERATED_OTHER "" PARENT_SCOPE)
    endif()
endfunction(fprime_python_setup_autocode)
