####
# autocoder/fprime_python.cmake:
#
# CMake implementation of an fprime autocoder used to generate Python bindings for components, types, etc. This
# autocoder uses the same autocoding criteria that the FPP autocoder uses, however; it assumes that the
# fprime-python-model compatible output has been generated in the build cache.
####
include_guard()
include(utilities)
include(autocoder/helpers)

# Invoke the autocoder once for each module containing FPP files.
autocoder_setup_for_multiple_sources()

####
# Function `is_supported`:
#
# Required function, processes module that contain FPP files.
# `AC_INPUT_FILE` potential input to the autocoder
####
function(fprime_python_is_supported AC_INPUT_FILE)
    autocoder_support_by_suffix(".fpp" "${AC_INPUT_FILE}" TRUE)
endfunction(fprime_python_is_supported)


####
# Function `fprime_python_setup_autocode`:
#
# Sets up the steps to run the autocoder and produce the files during the build. This is passed the lists generated
# in calls to `get_generated_files` and `get_dependencies`.
#
# AC_INPUT_FILES: list of supported autocoder input files
####
function(fprime_python_setup_autocode MODULE_NAME AC_INPUT_FILES)
    # Locate the fprime-python-ac tool and ensure it exists
    find_program(FPRIME_PYTHON_AC NAMES fprime-python-ac REQUIRED)
    fprime_cmake_ASSERT("'fprime-python-ac' not found" NOT "${FPRIME_PYTHON_AC}" MATCHES ".*-NOTFOUND")
    # Newer F Prime versions track build locations as a property of the global
    # interface target (populated as projects/libraries register), not as the
    # FPRIME_BUILD_LOCATIONS variable: read it at autocode time
    if (TARGET "${FPRIME_GLOBAL_INTERFACE_TARGET}")
        get_property(FPRIME_BUILD_LOCATIONS TARGET "${FPRIME_GLOBAL_INTERFACE_TARGET}" PROPERTY FPRIME_LOCATIONS)
    endif()
    # Execute in dry-run mode to get the list of files that would be generated
    execute_process(
        COMMAND "${FPRIME_PYTHON_AC}"
            "bindings"
            "${CMAKE_CURRENT_BINARY_DIR}"
            "--dry-run"
            "--output-directory" "${CMAKE_CURRENT_BINARY_DIR}"
            --prefixes ${FPRIME_BUILD_LOCATIONS}
            "--translation-units" ${AC_INPUT_FILES}
        OUTPUT_VARIABLE GENERATED_FILES_RAW
        COMMAND_ERROR_IS_FATAL ANY
    )
    # Process the output into a list and ensure that this is not an interface library (does not build anything)
    string(REPLACE " " ";" GENERATED_FILES_LIST "${GENERATED_FILES_RAW}")
    string(REPLACE "\n" "" GENERATED_FILES_LIST "${GENERATED_FILES_LIST}")
    get_target_property(MODULE_TYPE ${MODULE_NAME} TYPE)
    # Output was generated by this autocoder and we have a buildable module. Go ahead and set up the custom command.
    if (GENERATED_FILES_LIST AND NOT MODULE_TYPE STREQUAL "INTERFACE_LIBRARY")
        # Separate the generated files by type
        set(GENERATED_CPP_FILES "${GENERATED_FILES_LIST}")
        set(GENERATED_HPP_FILES "${GENERATED_FILES_LIST}")
        set(GENERATED_JSON_FILES "${GENERATED_FILES_LIST}")
        set(GENERATED_PY_FILES "${GENERATED_FILES_LIST}")
        list(FILTER GENERATED_CPP_FILES INCLUDE REGEX "^.*\\.cpp$")
        list(FILTER GENERATED_HPP_FILES INCLUDE REGEX "^.*\\.hpp$")
        list(FILTER GENERATED_JSON_FILES INCLUDE REGEX "^.*\\.json$")
        list(FILTER GENERATED_PY_FILES INCLUDE REGEX "^.*\\.py$")

        # Append to target properties for tracking
        append_list_property("${GENERATED_HPP_FILES}" TARGET "${MODULE_NAME}" PROPERTY FPRIME_PYTHON_GENERATED_HPP_FILES)
        append_list_property("${GENERATED_JSON_FILES}" TARGET "${MODULE_NAME}" PROPERTY FPRIME_PYTHON_GENERATED_JSON_FILES)
        append_list_property("${GENERATED_PY_FILES}" TARGET "${MODULE_NAME}" PROPERTY FPRIME_PYTHON_GENERATED_PY_FILES)

        add_custom_command(
            OUTPUT ${GENERATED_HPP_FILES} ${GENERATED_CPP_FILES} ${GENERATED_JSON_FILES} ${GENERATED_PY_FILES}
            DEPENDS ${AC_INPUT_FILES}
            COMMAND "${FPRIME_PYTHON_AC}"
                "bindings"
                "${CMAKE_CURRENT_BINARY_DIR}"
                "--output-directory" "${CMAKE_CURRENT_BINARY_DIR}"
                --prefixes ${FPRIME_BUILD_LOCATIONS}
                "--translation-units" ${AC_INPUT_FILES}
        )
        # Set the outputs for the autocoder:
        # - Dependencies are limited to (and require) pybind11
        # - Build sources are the generated CPP files
        # - Other generated files include HPP, JSON, and PY files
        set(AUTOCODER_DEPENDENCIES "pybind11::pybind11" PARENT_SCOPE)
        set(AUTOCODER_GENERATED_BUILD_SOURCES ${GENERATED_CPP_FILES} PARENT_SCOPE)
        # Generate HPP files as OTHER outputs since these technically are not built
        set(AUTOCODER_GENERATED_OTHER ${GENERATED_HPP_FILES} ${GENERATED_JSON_FILES} ${GENERATED_PY_FILES} PARENT_SCOPE)
    else()
        # No files were generated, set empty outputs
        set(AUTOCODER_DEPENDENCIES "" PARENT_SCOPE)
        set(AUTOCODER_GENERATED_BUILD_SOURCES "" PARENT_SCOPE)
        set(AUTOCODER_GENERATED_OTHER "" PARENT_SCOPE)
    endif()
endfunction(fprime_python_setup_autocode)
